"""Change client_message_id from UUID to String

Revision ID: d20447b4a48d
Revises: 
Create Date: 2026-01-28 15:02:08.053553

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd20447b4a48d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Удаляем server_default перед изменением типа
    op.alter_column('messages', 'client_message_id',
               existing_type=sa.UUID(),
               server_default=None)
    
    # Меняем тип колонки
    op.alter_column('messages', 'client_message_id',
               existing_type=sa.UUID(),
               type_=sa.String(),
               existing_nullable=False)
    op.create_index('ix_messages_chat_timestamp', 'messages', ['chat_id', 'server_timestamp'], unique=False)
    op.create_index('ix_messages_sender_chat', 'messages', ['sender_id', 'chat_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_messages_sender_chat', table_name='messages')
    op.drop_index('ix_messages_chat_timestamp', table_name='messages')
    op.alter_column('messages', 'client_message_id',
               existing_type=sa.String(),
               type_=sa.UUID(),
               existing_nullable=False,
               existing_server_default=sa.text('uuid_generate_v4()'))
    # ### end Alembic commands ###
